name : Main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.14.0.2'
      - run: sudo apt-get update && sudo apt-get install zsh texlive latexmk texlive-fonts-extra texlive-lang-european texlive-science
      - run: ./configure && make all
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { owner, repo } = context.repo
            const { data: { id } } = await github.repos.getLatestRelease({ owner, repo })
            await github.repos.deleteRelease({ owner, repo, release_id: id })
      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          body: "These are pdfs compiled from the most recent versions of the course material."
          name: Course materials
          tag_name: release
          files: |
            ./pdf/syllabus.pdf
            ./pdf/notes.pdf
            ./pdf/slides/part-1/lecture1.pdf
            ./pdf/slides/part-1/lecture2.pdf
            ./pdf/slides/part-1/lecture3.pdf
            ./pdf/slides/part-1/lecture4.pdf
            ./pdf/slides/part-1/lecture5.pdf
            ./pdf/slides/part-1/lecture6.pdf
            ./pdf/slides/part-2/lecture07.pdf
            ./pdf/slides/part-2/lecture08.pdf
            ./pdf/slides/part-2/lecture09.pdf
            ./pdf/slides/part-2/lecture10.pdf
            ./pdf/slides/part-2/lecture11.pdf
            ./pdf/slides/part-2/lecture12.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
